services:

  training-orchestrator:
    build:
      context: .
      dockerfile: training/Dockerfile

    container_name: intent-training-orchestrator

    env_file:
      - .env

    volumes:
      - ./customer-support-intent-classification-dataset:/app/customer-support-intent-classification-dataset
      - ./data:/app/data

    networks:
      - shared_network

networks:
  shared_network:
    name: intent_recognition_localstack_network
    external: true


volumes:
  localstack-data: