services:
  intent_recognition:
    build: .
    image: intent_recognition_img
    container_name: intent_recognition_container
    ports:
      - "5000:5000"
    volumes:
      - intent_recognition_vol:/usr/local/app/src/data
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"

volumes:
  intent_recognition_vol: