services:
  intent_recognition:
    build: .
    image: intent_recognition_img
    container_name: intent_recognition_container
    ports:
      - "5000:5000"
    volumes:
      - intent_recognition_vol:/usr/local/app/src/data
    env_file: 
        - /etc/app/app_env.env

    environment:
      - PYTHONUNBUFFERED=1

#     networks:
#       - shared_network

# networks:
#   shared_network:
#     name: intent_recognition_localstack_network
#     external: true

volumes:
  intent_recognition_vol: